# Generated by Django 2.1.4 on 2018-12-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', models.TextField(help_text='WKT representation of the polygon')),
                ('observation_time_start', models.DateTimeField()),
                ('observation_time_stop', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('swath_id', models.CharField(max_length=100)),
                ('timeliness', models.CharField(max_length=100)),
                ('station', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=100)),
                ('orbit_absolute', models.IntegerField()),
                ('orbit_relative', models.IntegerField()),
                ('scenes', models.IntegerField()),
                ('observation_duration', models.IntegerField()),
            ],
        ),
    ]
