# Generated by Django 2.1.3 on 2018-12-02 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181202_2122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationSettings',
        ),
    ]
