# Generated by Django 2.1.3 on 2018-12-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_requestimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestimage',
            name='image_path',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
