# Generated by Django 2.1.3 on 2018-12-04 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_dataset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestimage',
            name='processed_stap',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
