# Generated by Django 2.1.3 on 2018-12-04 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_requestimage_processed_stap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestimage',
            old_name='processed_stap',
            new_name='processed_stamp',
        ),
    ]
