# Generated by Django 2.1.3 on 2018-12-11 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_referenceimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestimage',
            name='id',
        ),
        migrations.AlterField(
            model_name='requestimage',
            name='dataset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.Dataset'),
        ),
    ]
