# Generated by Django 2.1.3 on 2018-12-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20181211_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceimage',
            name='image_path',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
