# Generated by Django 2.1.3 on 2018-12-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_referenceimage_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceimage',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
