# Generated by Django 2.1.3 on 2018-12-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_requestimage_result_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestimage',
            name='diff_summary_path',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='requestimage',
            name='histogram_path',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
