# Generated by Django 2.1.3 on 2018-12-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20181213_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestimage',
            name='template_match_score',
            field=models.FloatField(default=0),
        ),
    ]
