# Generated by Django 2.1.3 on 2018-12-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_requestimage_template_match_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestimage',
            name='diff_to_reference_score',
            field=models.TextField(default=''),
        ),
    ]
