# Generated by Django 2.1.3 on 2018-12-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_requestimage_diff_to_reference_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestimage',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requestimage',
            name='detected',
            field=models.BooleanField(default=False),
        ),
    ]
